### ISSUE TITLE
support for java8-runtime

### ISSUE THREAD

**Issue by hodiapa** [meltwater/puppet-marathon#15]
The newer versions of marathon requires JAVA 8 which is missing in this repo.

**Comment by salimane** [comment]
If you need java8, you could specify the java version with : 
```
class { '::marathon':
  ...
  install_java => true,
  java_version => 'java-1.8.0-openjdk',
}
```

Thanks

**Comment by hodiapa** [comment]
Hi, 
I am not able to find exactly in which .pp file that it handles the installation of the java_version? Does it depend on external module to do the java installation? 

Thanks,

**Comment by salimane** [comment]
``puppet-marathon`` expects that the version you are specify is available with your package manager. On centos you could try include the ``epel`` repositories. The java installation is handled here ``https://github.com/meltwater/puppet-marathon/blob/master/manifests/install.pp``
Thanks

**Comment by hodiapa** [comment]
Thanks for the response. Shouldn't that be a dependency or be specified in the Readme explicitly.

Also as per this: http://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts
openjdk-8 package is still missing in the ubuntu 14.04 LTS packages.

Thanks

**Comment by salimane** [comment]
I would always love a pull request for this :)
Thanks
